services:
  quizapp:
    image: viktorsaveski7/quizapp:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/questionb
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })' || exit 1" ]
      interval: 10s
      retries: 10
      timeout: 10s

volumes:
  db_data: