apiVersion: v1
kind: ConfigMap
metadata:
  name: quizapp-config
  namespace: quiz
data:
  application.properties: |
    spring.data.mongodb.host=mongo
    spring.data.mongodb.port=27017
    spring.data.mongodb.database=questionb
    spring.data.mongodb.uri=mongodb://mongo-0.mongo.quiz.svc.cluster.local:27017,mongo-1.mongo.quiz.svc.cluster.local:27017,mongo-2.mongo.quiz.svc.cluster.local:27017/questionb?replicaSet=rs0
